// Rebuild the portable assets from vortex.js. No dependencies required.
const fs = require("node:fs");
const path = require("node:path");
const geometry = require("./vortex.js");
const check = process.argv.includes("--check");
const point = p => `CGPoint(x: ${p[0]}, y: ${p[1]})`;
const swift = `// Provenance: HAND-BUILT. Built from: SwiftUI Shape, Path, cubic Bézier geometry.
// Generated by node logo/build.cjs from vortex.js. Edit the source geometry there.
import SwiftUI

/// A centered, resolution-independent vortex that uses roughly 91–95% of its square.
/// Fill with any ShapeStyle. Animate collapse from 0 (vortex) to 1 (dot).
struct MaxVortex: Shape {
    var collapse: CGFloat = 0

    var animatableData: CGFloat {
        get { collapse }
        set { collapse = newValue }
    }

    func path(in rect: CGRect) -> Path {
        let side = min(rect.width, rect.height)
        guard side > 0 else { return Path() }
        let progress = min(1, max(0, collapse))
        if progress == 1 {
            let radius = side * Self.dotRadius / 100
            return Path(ellipseIn: CGRect(
                x: rect.midX - radius, y: rect.midY - radius,
                width: radius * 2, height: radius * 2
            ))
        }

        func point(_ index: Int) -> CGPoint {
            let start = Self.blade[index]
            let end = Self.dot[index]
            return CGPoint(
                x: start.x + (end.x - start.x) * progress,
                y: start.y + (end.y - start.y) * progress
            )
        }

        var arm = Path()
        arm.move(to: point(0))
        for index in stride(from: 1, to: Self.blade.count, by: 3) {
            arm.addCurve(to: point(index + 2), control1: point(index), control2: point(index + 1))
        }
        arm.closeSubpath()

        var result = Path()
        for index in 0..<${geometry.armCount} {
            let transform = CGAffineTransform(translationX: rect.midX, y: rect.midY)
                .scaledBy(x: side / 100, y: side / 100)
                .rotated(by: CGFloat(index) * .pi / 3)
            result.addPath(arm, transform: transform)
        }
        return result
    }

    private static let dotRadius: CGFloat = ${geometry.dotRadius}
    private static let blade: [CGPoint] = [
${geometry.points.map(p => `        ${point(p)},`).join("\n")}
    ]

    private static let dot: [CGPoint] = {
        let count = (blade.count - 1) / 3
        let step = 2 * CGFloat.pi / CGFloat(count)
        var points = [CGPoint(x: 0, y: -dotRadius)]
        for index in 0..<count {
            let a = -CGFloat.pi / 2 + CGFloat(index) * step
            let b = a + step
            let handle = 4 / 3 * tan(step / 4) * dotRadius
            let start = CGPoint(x: cos(a) * dotRadius, y: sin(a) * dotRadius)
            let end = CGPoint(x: cos(b) * dotRadius, y: sin(b) * dotRadius)
            points.append(CGPoint(x: start.x - sin(a) * handle, y: start.y + cos(a) * handle))
            points.append(CGPoint(x: end.x + sin(b) * handle, y: end.y - cos(b) * handle))
            points.append(end)
        }
        return points
    }()
}
`;
for (const [name, source] of [
  ["max-vortex.svg", `<?xml version="1.0" encoding="UTF-8"?>\n${geometry.svg()}\n`],
  ["../max-app/max-app/Shared/DesignSystem/MaxVortex.swift", swift],
  ["../max-app/max-app/AppIcon.icon/Assets/vortex.svg",
    `<?xml version="1.0" encoding="UTF-8"?>\n${geometry.svg({ color: "#000000" })}\n`],
  ["../max-app/max-app/Assets.xcassets/LogoMark.imageset/logo-mark.svg",
    `<?xml version="1.0" encoding="UTF-8"?>\n${geometry.svg({ size: 18, color: "#000000" })}\n`]
]) {
  const target = path.join(__dirname, name);
  if (check) {
    if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== source) {
      throw new Error(`${name} is out of date; run node logo/build.cjs`);
    }
  } else fs.writeFileSync(target, source);
}
console.log(check ? "Preview and app assets match the source geometry." : "Built preview and app vortex assets.");
