// Generated by node logo/build.cjs from vortex.js. Edit the source geometry there.
import SwiftUI

/// A centered, resolution-independent vortex that uses roughly 91–95% of its square.
/// Fill with any ShapeStyle. Animate collapse from 0 (vortex) to 1 (dot).
struct MaxVortex: Shape {
    var collapse: CGFloat = 0

    var animatableData: CGFloat {
        get { collapse }
        set { collapse = newValue }
    }

    func path(in rect: CGRect) -> Path {
        let side = min(rect.width, rect.height)
        guard side > 0 else { return Path() }
        let progress = min(1, max(0, collapse))
        if progress == 1 {
            let radius = side * Self.dotRadius / 100
            return Path(ellipseIn: CGRect(
                x: rect.midX - radius, y: rect.midY - radius,
                width: radius * 2, height: radius * 2
            ))
        }

        func point(_ index: Int) -> CGPoint {
            let start = Self.blade[index]
            let end = Self.dot[index]
            return CGPoint(
                x: start.x + (end.x - start.x) * progress,
                y: start.y + (end.y - start.y) * progress
            )
        }

        var arm = Path()
        arm.move(to: point(0))
        for index in stride(from: 1, to: Self.blade.count, by: 3) {
            arm.addCurve(to: point(index + 2), control1: point(index), control2: point(index + 1))
        }
        arm.closeSubpath()

        var result = Path()
        for index in 0..<6 {
            let transform = CGAffineTransform(translationX: rect.midX, y: rect.midY)
                .scaledBy(x: side / 100, y: side / 100)
                .rotated(by: CGFloat(index) * .pi / 3)
            result.addPath(arm, transform: transform)
        }
        return result
    }

    private static let dotRadius: CGFloat = 4
    private static let blade: [CGPoint] = [
        CGPoint(x: 10.32181, y: -45.24972),
        CGPoint(x: 12.92447, y: -45.44447),
        CGPoint(x: 15.73923, y: -45.38896),
        CGPoint(x: 17.9263, y: -44.52665),
        CGPoint(x: 20.08534, y: -43.6754),
        CGPoint(x: 21.63267, y: -42.0379),
        CGPoint(x: 22.23133, y: -39.85861),
        CGPoint(x: 22.83, y: -37.67932),
        CGPoint(x: 22.47999, y: -34.95824),
        CGPoint(x: 21.01608, y: -33.49925),
        CGPoint(x: 19.55217, y: -32.04026),
        CGPoint(x: 16.97435, y: -31.84336),
        CGPoint(x: 14.31879, y: -31.71701),
        CGPoint(x: 11.62874, y: -31.58901),
        CGPoint(x: 8.85891, y: -31.5334),
        CGPoint(x: 6.59402, y: -30.88873),
        CGPoint(x: 4.35816, y: -30.25232),
        CGPoint(x: 2.61437, y: -29.04185),
        CGPoint(x: 1.02243, y: -27.7155),
        CGPoint(x: -0.56951, y: -26.38915),
        CGPoint(x: -2.00961, y: -24.9469),
        CGPoint(x: -2.85973, y: -22.91961),
        CGPoint(x: -3.2903, y: -21.8928),
        CGPoint(x: -3.56953, y: -20.71591),
        CGPoint(x: -3.72054, y: -19.41969),
        CGPoint(x: -3.86769, y: -18.15672),
        CGPoint(x: -3.89311, y: -16.78046),
        CGPoint(x: -4.19522, y: -15.60317),
        CGPoint(x: -4.50528, y: -14.3949),
        CGPoint(x: -5.10679, y: -13.3962),
        CGPoint(x: -6.03528, y: -12.85094),
        CGPoint(x: -6.96378, y: -12.30569),
        CGPoint(x: -8.21927, y: -12.21388),
        CGPoint(x: -9.25223, y: -12.57003),
        CGPoint(x: -11.29168, y: -13.2732),
        CGPoint(x: -12.46373, y: -15.72256),
        CGPoint(x: -13.03796, y: -18.15474),
        CGPoint(x: -14.18642, y: -23.01911),
        CGPoint(x: -12.9436, y: -27.81479),
        CGPoint(x: -10.95682, y: -31.79432),
        CGPoint(x: -6.97035, y: -39.7792),
        CGPoint(x: 0.01131, y: -44.47822),
        CGPoint(x: 10.32181, y: -45.24972),
    ]

    private static let dot: [CGPoint] = {
        let count = (blade.count - 1) / 3
        let step = 2 * CGFloat.pi / CGFloat(count)
        var points = [CGPoint(x: 0, y: -dotRadius)]
        for index in 0..<count {
            let a = -CGFloat.pi / 2 + CGFloat(index) * step
            let b = a + step
            let handle = 4 / 3 * tan(step / 4) * dotRadius
            let start = CGPoint(x: cos(a) * dotRadius, y: sin(a) * dotRadius)
            let end = CGPoint(x: cos(b) * dotRadius, y: sin(b) * dotRadius)
            points.append(CGPoint(x: start.x - sin(a) * handle, y: start.y + cos(a) * handle))
            points.append(CGPoint(x: end.x + sin(b) * handle, y: end.y - cos(b) * handle))
            points.append(end)
        }
        return points
    }()
}
